# Generated by Django 5.2.7 on 2025-11-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=10)),
                ('runtime', models.CharField(max_length=100)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('songs', models.JSONField(default=list)),
                ('colours', models.JSONField(default=list)),
            ],
        ),
    ]
